version: "3.8"
services:

  php8:
      container_name: php8-symrecipe
      build: docker
      ports:
          - "8000:8000"
      volumes:
          - ./:/var/www
          - /var/www/project/vendor
          - /var/www/project/var
      networks:
      - dev
  db:
    image: mysql:latest
    container_name: mysql-symrecipe
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_name
    ports:
      - 3306:3306
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin-symrecipe
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    networks:
      - dev

  mailer:
    image: schickling/mailcatcher
    ports: [1025, 1080]

networks:
  dev: